/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * howToPlayForm.java
 *
 * Created on Dec 12, 2012, 8:44:31 PM
 */

package casinoroyale;

/**
 *
 * @author smg5498
 */
public class HowToPlayForm extends javax.swing.JFrame {

    /** Creates new form howToPlayForm */
    public HowToPlayForm() {
        initComponents();
        howToPlayArea.append("• Actions  "
                + "\n\t oFold – withdraw your hand from the game."
                + "\n\t oBet – Either sets or raises the amount wagered"
                + "\n\t oCheck – does not bet but lets the next player dictate betting. "
                + "\n\t oDiscard – discards the selected cards for new ones.  Only limited to draw poker."
                + "\n\t oConnect to Server – Connects player client to the host player."
                + "\n\nGames "
                + "\n• 5 Card Draw"
                + "\n\t oPlayers are dealt 5 cards face down.  "
                + "\n\t oAfter a round of betting, remaining players may trade up to 3 cards for new ones."
                + "\n\t oAnother round of betting happens."
                + "\nPlayer with the best 5 card hand wins"
                + "\n\n• Texas Hold’em"
                + "\n\t oPlayers are dealt 2 cards facedown."
                + "\n\t oA round of betting happens."
                + "\n\t oThe flop is then dealt, 3 community cards face up."
                + "\n\t oA round of betting happens ."
                + "\n\t oThe river card is added to the face up community cards."
                + "\n\t oAnother round of betting happens."
                + "\n\t oThe turn card is added to the community cards."
                + "\n• Omaha Hold’em"
                + "\n\t oPlayers are dealt 4 cards facedown."
                + "\n\t oA round of betting happens."
                + "\n\t oThe flop is then dealt, 3 community cards face up."
                + "\n\t oA round of betting happens ."
                + "\n\t oThe river card is added to the face up community cards."
                + "\n\t oAnother round of betting happens."
                + "\n\t oThe turn card is added to the community cards."
                + "\n• Countdown Poker"
                + "\n\t oPlayers are dealt 5 cards facedown."
                + "\n\t oA round of betting happens."
                + "\n\t oAfter a round of betting, remaining players may trade up to 3 cards for new ones."
                + "\n\t oAnother round of betting happens."
                + "\n\t oAfter a round of betting, remaining players may trade up to 2 cards for new ones."
                + "\n\t oAnother round of betting happens."
                + "\n\t oAfter a round of betting, remaining players may trade up to 1 card for a new one."
                + "\n\t oThere is a final round of betting."
                + "\n\t oThe player with the best 5 card hand wins."
                + "\n\nIf every player passes, then the next player deals a new hand to all of the players."
                + "\n\nIn 5 card draw, a player may not request more than 3 cards during the trade in round.");

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        howToPlayArea = new javax.swing.JTextArea();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(576, 433));
        setResizable(false);

        howToPlayArea.setColumns(20);
        howToPlayArea.setEditable(false);
        howToPlayArea.setRows(5);
        jScrollPane1.setViewportView(howToPlayArea);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        getContentPane().add(okButton, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_okButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HowToPlayForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea howToPlayArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables

}
